### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by cn-johndpope** [rametta/rapini#33]
```
(spleeter) ➜  react-native git:(react-native) ✗ npx rapini react-query -p openapi.yaml
Generating React Query v3 package using OpenApi file openapi.yaml
API name: SETFlowAPI, Version: 1.0
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createFunctionDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/common/util.js:253
        .split("-")
         ^

TypeError: Cannot read properties of undefined (reading 'split')
    at normalizeOperationId (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/common/util.js:253:10)
    at makeRequest (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/common/requests.js:247:150)
    at makeRequestsPropertyAssignment (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/common/requests.js:85:23)
    at /Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/common/requests.js:28:16
    at Array.flatMap (<anonymous>)
    at makeRequests (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/common/requests.js:26:42)
    at parseOpenApiV3Doc (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/react-query/generator.js:91:47)
    at parse (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/react-query/generator.js:83:16)
    at /Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/react-query/generator.js:126:28
    at step (/Users/johndpope/.npm/_npx/d88112f5ad5f60bf/node_modules/rapini/dist/react-query/generator.js:33:23)

Node.js v18.14.0


```
any help would be great.

https://gist.github.com/cn-johndpope/3597fb777ce43041801d661ca4b75ca7

node 10 - also not working.

npx rapini react-query -p openapi.yaml
npx: installed 25 in 4.631s
Generating React Query v3 package using OpenApi file openapi.yaml
API name: SETFlowAPI, Version: 1.0
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
(node:18087) UnhandledPromiseRejectionWarning: TypeError: operationId.split(...).flatMap is not a function
    at normalizeOperationId (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/common/util.js:254:10)
    at makeQueryId (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/common/queryIds.js:87:65)
    at /Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/common/queryIds.js:43:16
    at Array.map (<anonymous>)
    at makeQueryIds (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/common/queryIds.js:41:10)
    at parseOpenApiV3Doc (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/react-query/generator.js:90:47)
    at parse (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/react-query/generator.js:83:16)
    at /Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/react-query/generator.js:126:28
    at step (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/react-query/generator.js:33:23)
    at Object.next (/Users/johndpope/.npm/_npx/18087/lib/node_modules/rapini/dist/react-query/generator.js:14:53)
(node:18087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18087) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cn-johndpope** [comment]
operationId: postConfig
operationId: getWatchlist
operationId: postWatchlist
operationId: postwatchlistnote
operationId: getWhatsNew
operationId: getWidget
operationId: postWidget
operationId: postcpuserlog
operationId: getConsumptionType
operationId: getUtilityList
operationId: postaccountlookup
operationId: postBudget
operationId: postCustomerPortal
operationId: postCustomerPortaluserUUID
operationId: postcustomerdetails
operationId: postcreateuser
operationId: postcreatecpuser
operationId: getSsoLogin
operationId: postlogin
operationId: getUserInfo
operationId: getUserContactMethods
operationId: postusercontactmethod
operationId: postsubmitdisconnectinfo
operationId: postsendsupportmessage
**operationId: undefined**


function normalizeOperationId(operationId) {
    console.log("operationId:",operationId);
    var split = operationId
        .split("-")
        .flatMap(function (x) { return x.split("_"); })
        .map(function (x, i) {
        return i === 0 ? lowercaseFirstLetter(x) : capitalizeFirstLetter(x);
    });
    return split.join("");
}
